baseurl = "https://nia.dev"
title = "Fluffy Samurai"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Nia"
    info = "Software Engineer | she/her"
    description = "Nia's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"
    disable_comments = true

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "You can't take the sky from me"

    hidecredits = true
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/fluffy-samurai/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/fluffy-samurai/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/fluffysamurai/"
[[params.social]]
    name = "Keybase"
    icon = "fab fa-keybase fa-2x"
    weight = 4
    url = "https://keybase.io/fluffy_samurai"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
